- id: eclipse-formatter
  name: Eclipse Java Formatter
  description: This hook formats Java code with the Eclipse formatter.
  entry: eclipse-formatter
  language: python
  types:
    - java
- id: google-java-formatter
  name: Google Java Formatter
  description: This hook formats Java code with Google Java Formatter.
  entry: google-java-formatter
  language: python
  language_version: python3
  types:
    - java
- id: commitlint
  name: Commitlint
  description: Lint commit messages according to the conventional conventions
  entry: extenda/commitlint
  language: docker_image
- id: vale
  name: Vale lint
  description: Lint natural language with the Extenda Retail writing style
  entry: extenda/vale
  language: docker_image
